const METIER_QUESTIONS = {
  "Ouvrier Polyvalent": [
    "Sécurisation de son poste de travail",
    "Préparation du travail",
    "Approvisionnement de son poste de travail",
    "Lecture et compréhension des plans",
    "Coffrage",
    "Décoffrage",
    "Ferraillage",
    "Bétonnage",
    "Utilisation des ponts-roulants",
    "Qualité du travail",
    "Respect des consignes émises par son supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect des prescriptions environnementales",
    "Capacité d’intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives, volonté d’apprendre",
    "Sens des responsabilités",
    "Soin apporté aux équipements et matériels confiés"
  ],

  "Coffreur/Ferrailleur": [
    "Sécurisation de son poste de travail",
    "Préparation du travail",
    "Approvisionnement de son poste de travail",
    "Lecture et compréhension des plans",
    "Coffrage",
    "Décoffrage",
    "Ferraillage",
    "Bétonnage",
    "Montage des structures porteuses",
    "Utilisation d’engins motorisés",
    "Qualité du travail",
    "Respect des consignes émises par son supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect des prescriptions environnementales",
    "Intégration dans l’équipe et sur chantier",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin aux équipements confiés"
  ],

  "Électricien": [
    "Sécurisation de son poste de travail",
    "Approvisionnement de son poste de travail",
    "Lecture et compréhension des plans, schémas",
    "Pose de chemins de câbles / conduits électriques",
    "Câblage d’armoires / tableaux",
    "Équipement d’armoires électriques industrielles",
    "Raccordement équipements basse tension",
    "Raccordement équipements industriels",
    "Mise sous tension et contrôles",
    "Utilisation d’appareils de mesure",
    "Qualité du travail",
    "Respect des consignes en atelier / chantier",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect des prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ],

  "Grutier": [
    "Contrôle fondation / horizontalité",
    "Contrôle verticalité du mât",
    "Contrôle mise à la terre",
    "Contrôle des lests",
    "Contrôle dispositifs de sécurité",
    "Contrôle sécurité du crochet",
    "Contrôle câble de levage",
    "Tracé de déplacement des charges",
    "Distribution des charges",
    "Utilisation engins non motorisés",
    "Qualité du travail",
    "Respect des consignes du supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Aide aux collègues (grue à l’arrêt)",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ],

  "Maçon": [
    "Sécurisation de son poste de travail",
    "Préparation du travail",
    "Approvisionnement",
    "Lecture et compréhension des plans",
    "Techniques d’application d’enduit",
    "Maçonnerie blocs",
    "Maçonnerie parement",
    "Techniques de traçage",
    "Montage des structures porteuses",
    "Utilisation d’échafaudages",
    "Utilisation d’engins motorisés",
    "Qualité du travail",
    "Respect des consignes du supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ],

  "Manœuvre": [
    "Sécurisation de son poste de travail",
    "Préparation du travail",
    "Approvisionnement",
    "Déchargement manuel des matériaux",
    "Démolition avec machine",
    "Mélanges mortier / béton",
    "Outils manuels de terrassement",
    "Engins non motorisés",
    "Marteau-piqueur",
    "Montage structures porteuses",
    "Qualité du travail",
    "Respect des consignes du supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ],

  "Opérateur de cour": [
    "Sécurisation de son poste de travail",
    "Préparation du travail",
    "Approvisionnement",
    "Déchargement manuel",
    "Engins non motorisés",
    "Engins motorisés (clark, manitou...)",
    "Contrôle sécurité crochet levage",
    "Contrôle câble de levage",
    "Distribution précise des charges",
    "Qualité du travail",
    "Respect des consignes du supérieur",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ],

  "Soudeur": [
    "Sécurisation de son poste de travail",
    "Approvisionnement",
    "Lecture et compréhension des plans",
    "Vérification matériel / réglage paramètres",
    "Techniques de soudure",
    "Appareils de métrologie",
    "Outillages électroportatifs",
    "Montage électrique et mécanique",
    "Qualité du travail",
    "Tri et évacuation des déchets",
    "Ponctualité",
    "Respect des consignes de sécurité",
    "Respect prescriptions environnementales",
    "Intégration dans l’équipe",
    "Respect des délais",
    "Assiduité",
    "Prise d’initiatives",
    "Sens des responsabilités",
    "Soin au matériel"
  ]
};
